export const abi = [
  {
    type: 'function',
    name: 'activePlayers',
    inputs: [],
    outputs: [{ name: 'active', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'addPlayer',
    inputs: [{ name: 'playerAddr', type: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'addrToId',
    inputs: [{ name: 'addr', type: 'address' }],
    outputs: [{ name: '', type: 'int8' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'canJoin',
    inputs: [],
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'canLeave',
    inputs: [],
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'commit',
    inputs: [
      { name: 'pick_', type: 'uint8' },
      { name: 'salt_', type: 'bytes32' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'factory',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'init',
    inputs: [{ name: 'factory_', type: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'isActive',
    inputs: [],
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'isFinalized',
    inputs: [],
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'pick',
    inputs: [{ name: 'proof_', type: 'bytes32' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'player',
    inputs: [{ name: '', type: 'uint256' }],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'removePlayer',
    inputs: [{ name: 'playerAddr', type: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'rps',
    inputs: [
      { name: 'a', type: 'uint8' },
      { name: 'b', type: 'uint8' },
    ],
    outputs: [
      { name: 'isTie', type: 'bool' },
      { name: 'winner', type: 'uint8' },
    ],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    name: 'totalPlayers',
    inputs: [],
    outputs: [{ name: 'total', type: 'uint256' }],
    stateMutability: 'pure',
  },
] as const
