/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const WalletLazyImport = createFileRoute('/wallet')()
const FreeplayLazyImport = createFileRoute('/freeplay')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const WalletLazyRoute = WalletLazyImport.update({
  path: '/wallet',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/wallet.lazy').then((d) => d.Route))

const FreeplayLazyRoute = FreeplayLazyImport.update({
  path: '/freeplay',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/freeplay.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/freeplay': {
      id: '/freeplay'
      path: '/freeplay'
      fullPath: '/freeplay'
      preLoaderRoute: typeof FreeplayLazyImport
      parentRoute: typeof rootRoute
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  FreeplayLazyRoute,
  WalletLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/freeplay",
        "/wallet"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/freeplay": {
      "filePath": "freeplay.lazy.tsx"
    },
    "/wallet": {
      "filePath": "wallet.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
