/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const WalletLazyImport = createFileRoute('/wallet')()
const GamesLazyImport = createFileRoute('/games')()
const FreeplayLazyImport = createFileRoute('/freeplay')()
const IndexLazyImport = createFileRoute('/')()
const GamesIndexLazyImport = createFileRoute('/games/')()
const GamesMyLazyImport = createFileRoute('/games/my')()
const GamesAddrLazyImport = createFileRoute('/games/$addr')()

// Create/Update Routes

const WalletLazyRoute = WalletLazyImport.update({
  path: '/wallet',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/wallet.lazy').then((d) => d.Route))

const GamesLazyRoute = GamesLazyImport.update({
  path: '/games',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/games.lazy').then((d) => d.Route))

const FreeplayLazyRoute = FreeplayLazyImport.update({
  path: '/freeplay',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/freeplay.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const GamesIndexLazyRoute = GamesIndexLazyImport.update({
  path: '/',
  getParentRoute: () => GamesLazyRoute,
} as any).lazy(() => import('./routes/games/index.lazy').then((d) => d.Route))

const GamesMyLazyRoute = GamesMyLazyImport.update({
  path: '/my',
  getParentRoute: () => GamesLazyRoute,
} as any).lazy(() => import('./routes/games/my.lazy').then((d) => d.Route))

const GamesAddrLazyRoute = GamesAddrLazyImport.update({
  path: '/$addr',
  getParentRoute: () => GamesLazyRoute,
} as any).lazy(() => import('./routes/games/$addr.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/freeplay': {
      id: '/freeplay'
      path: '/freeplay'
      fullPath: '/freeplay'
      preLoaderRoute: typeof FreeplayLazyImport
      parentRoute: typeof rootRoute
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesLazyImport
      parentRoute: typeof rootRoute
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletLazyImport
      parentRoute: typeof rootRoute
    }
    '/games/$addr': {
      id: '/games/$addr'
      path: '/$addr'
      fullPath: '/games/$addr'
      preLoaderRoute: typeof GamesAddrLazyImport
      parentRoute: typeof GamesLazyImport
    }
    '/games/my': {
      id: '/games/my'
      path: '/my'
      fullPath: '/games/my'
      preLoaderRoute: typeof GamesMyLazyImport
      parentRoute: typeof GamesLazyImport
    }
    '/games/': {
      id: '/games/'
      path: '/'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexLazyImport
      parentRoute: typeof GamesLazyImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  FreeplayLazyRoute,
  GamesLazyRoute: GamesLazyRoute.addChildren({
    GamesAddrLazyRoute,
    GamesMyLazyRoute,
    GamesIndexLazyRoute,
  }),
  WalletLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/freeplay",
        "/games",
        "/wallet"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/freeplay": {
      "filePath": "freeplay.lazy.tsx"
    },
    "/games": {
      "filePath": "games.lazy.tsx",
      "children": [
        "/games/$addr",
        "/games/my",
        "/games/"
      ]
    },
    "/wallet": {
      "filePath": "wallet.lazy.tsx"
    },
    "/games/$addr": {
      "filePath": "games/$addr.lazy.tsx",
      "parent": "/games"
    },
    "/games/my": {
      "filePath": "games/my.lazy.tsx",
      "parent": "/games"
    },
    "/games/": {
      "filePath": "games/index.lazy.tsx",
      "parent": "/games"
    }
  }
}
ROUTE_MANIFEST_END */
